version: "3.7"

services:
  ##### MySQL #####
  # https://hub.docker.com/_/mysql
  # Help:
  # > mysql -u root -p
  mysql:
    image: mysql:8.0
    command: [--default-authentication-plugin=mysql_native_password]
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecr3t
    ports:
    - 3306:3306
    - 33060:33060
    volumes:
    - ./samples/mysql/:/docker-entrypoint-initdb.d/
    - mysql_data:/var/lib/mysql

  ##### PostgreSQL #####
  # https://hub.docker.com/_/postgres
  # Help:
  # > psql -U postgres [-W]
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: SuperSecr3t
    ports:
    - 5432:5432
    volumes:
    - ./samples/postgres/:/docker-entrypoint-initdb.d/
    - postgres_data:/var/lib/postgresql/data

  hive-metastore:
    image: dungdm93/hive:3.1.2
    # HOTFIX: Illegal character in hostname at index 13: thrift://hive_hive-metastore_1.bookshelf:9083
    # Caused at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.resolveUris(HiveMetaStoreClient.java:267)
    container_name: hive-metastore
    entrypoint: ["/usr/local/scripts/metastore-entrypoint.sh"]
    depends_on:
    - postgres
    environment:
      HADOOP_OPTIONAL_TOOLS: hadoop-aws
    ports:
    - 9083:9083
    volumes:
    - ./scripts/hive/:/usr/local/scripts/
    - ./configs/hive/:/opt/hive/conf/
    - warehouse_data:/data/warehouse

  hive-server2:
    image: dungdm93/hive:3.1.2
    entrypoint: ["/usr/local/scripts/hiveserver2-entrypoint.sh"]
    depends_on:
    - hive-metastore
    environment:
      HADOOP_OPTIONAL_TOOLS: hadoop-aws
    ports:
    - 10000:10000
    - 10002:10002 # WebUI
    volumes:
    - ./scripts/hive/:/usr/local/scripts/
    - ./configs/hive/:/opt/hive/conf/
    - warehouse_data:/data/warehouse

  ##### TrinoDB #####
  # https://hub.docker.com/r/trinodb/trino
  # Help:
  # > trino --server=localhost:8080 [--catalog=mysql] [--schema=sakila]
  trino:
    image: trinodb/trino:362
    ports:
    - 8080:8080
    volumes:
    - ./configs/trino/:/etc/trino/
    - warehouse_data:/data/warehouse

  ##### Apache SuperSet #####
  # Create an admin user
  # > superset fab create-admin
  # Load some data to play with
  # > superset load_examples
  # Create default roles and permissions
  # > superset init
  superset:
    image: dungdm93/superset:1.0
    command: [webserver]
    environment:
      SUPERSET_CONFIG_PATH: /etc/superset/superset_config.py
      CELERY_CONFIG_PATH: /etc/superset/celeryconfig.py
      PYTHONPATH: /app/
    ports:
    - 8088:8088
    volumes:
    - ./configs/superset:/etc/superset
    - ../:/app/

volumes:
  mysql_data:
  postgres_data:
  warehouse_data:

networks:
  default:
    name: bookshelf
